AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
